DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS recipe CASCADE;
DROP TABLE IF EXISTS ingredients CASCADE;

CREATE TABLE users (
id SERIAL PRIMARY KEY NOT NULL,
name VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
password VARCHAR(50) NOT NULL
);

CREATE TABLE recipe (
recipe_id SERIAL PRIMARY KEY NOT NULL,
user_id INT NOT NULL,
image_url VARCHAR(50) NOT NULL,
prep_time VARCHAR(50) NOT NULL,
serving_size VARCHAR(50) NOT NULL,
category VARCHAR(50) NOT NULL,
preparation VARCHAR(50) NOT NULL,
fat VARCHAR(50) NOT NULL,
carbs VARCHAR(50) NOT NULL,
protein VARCHAR(50) NOT NULL
);

CREATE TABLE ingredients (
ingredient_id SERIAL PRIMARY KEY NOT NULL,
ingridient_name VARCHAR(50) NOT NULL
);